# docker-compose.yml
version: "3.8"

services:
  racoondevs-backend:
    build: .
    container_name: racoondevs-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - ./back/.env
    volumes:
      - ./logs:/app/logs
    networks:
      - racoondevs-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  racoondevs-network:
    driver: bridge

volumes:
  logs:
